
sudo: true

#language: java

install:
- ls -ltrh /usr/share/fonts/    
- export path1=some-value
- wget https://github.com/standup75/standupweb-cms/raw/master/css/BAUHS93.TTF
- ls -ltrh 
- sudo cp BAUHS93.TTF /usr/share/fonts/
- ls -ltrh /usr/local/share/fonts/
- ls -ltrh /usr/share/fonts/
- echo $path1
- fc-list | grep -i auhaus

script:
- echo $path1
